use super::*;

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct ReceiptBackfillEntry {
    pub(crate) task_id: String,
    pub(crate) title: String,
    pub(crate) missing_reasons: Vec<String>,
    pub(crate) review_handoff_missing: bool,
    pub(crate) verification_commands: Vec<String>,
    pub(crate) wrapper_commands: Vec<String>,
}

pub(crate) fn run_parallel_receipt_backfill(args: &ParallelArgs) -> Result<()> {
    let repo_root = git_repo_root()?;
    ensure_repo_layout(&repo_root)?;
    let run_root = parallel_run_root(&repo_root, args);
    ensure_writable_run_root(&run_root)?;

    let plan_text = read_loop_plan(&repo_root)?;
    let snapshot = parse_loop_plan(&plan_text);
    let mut entries = receipt_backfill_entries(&repo_root, &snapshot);
    let mut applied_handoffs = Vec::new();

    if args.apply_receipt_backfill_handoffs {
        for task in snapshot
            .tasks
            .iter()
            .filter(|task| task.status == LoopTaskStatus::Done)
        {
            let evidence = inspect_task_completion_evidence(&repo_root, &task.id, &task.markdown);
            if evidence.has_review_handoff {
                continue;
            }
            let mut review_evidence = evidence.clone();
            review_evidence.has_review_handoff = true;
            if ensure_host_review_handoff(
                &repo_root,
                &task.id,
                &review_handoff_changed_files(&review_evidence),
                &review_evidence,
            )? {
                applied_handoffs.push(task.id.clone());
            }
        }
        if !applied_handoffs.is_empty() {
            run_git(&repo_root, ["add", "REVIEW.md"])?;
            entries = receipt_backfill_entries(&repo_root, &snapshot);
        }
    }

    let report = render_receipt_backfill_report(
        &repo_root,
        args.apply_receipt_backfill_handoffs,
        &applied_handoffs,
        &entries,
    );
    let report_path = run_root.join("receipt-backfill.md");
    atomic_write(&report_path, report.as_bytes())
        .with_context(|| format!("failed to write {}", report_path.display()))?;

    println!("receipt backfill report: {}", report_path.display());
    if entries.is_empty() {
        println!("receipt backfill: no completed task drift detected");
    } else {
        println!(
            "receipt backfill: {} completed task(s) need evidence repair",
            entries.len()
        );
        if !applied_handoffs.is_empty() {
            println!(
                "receipt backfill: applied REVIEW.md handoff(s) for {}",
                applied_handoffs.join(", ")
            );
            println!("receipt backfill: REVIEW.md is staged; commit after review");
        }
    }
    Ok(())
}

pub(crate) fn receipt_backfill_entries(
    repo_root: &Path,
    snapshot: &LoopPlanSnapshot,
) -> Vec<ReceiptBackfillEntry> {
    snapshot
        .tasks
        .iter()
        .filter(|task| task.status == LoopTaskStatus::Done)
        .filter_map(|task| {
            let evidence = inspect_task_completion_evidence(repo_root, &task.id, &task.markdown);
            if evidence.is_fully_evidenced() {
                return None;
            }
            let verification = verification_plan(&task.markdown);
            let wrapper_commands = verification
                .executable_commands
                .iter()
                .map(|command| render_receipt_wrapper_command(&task.id, command))
                .collect::<Vec<_>>();
            Some(ReceiptBackfillEntry {
                task_id: task.id.clone(),
                title: task.title.clone(),
                missing_reasons: evidence.missing_reasons(),
                review_handoff_missing: !evidence.has_review_handoff,
                verification_commands: verification.executable_commands,
                wrapper_commands,
            })
        })
        .collect()
}

pub(crate) fn render_receipt_backfill_report(
    repo_root: &Path,
    apply_handoffs: bool,
    applied_handoffs: &[String],
    entries: &[ReceiptBackfillEntry],
) -> String {
    let wrapper_present = repo_root.join("scripts/run-task-verification.sh").exists();
    let recorder_present = repo_root.join("scripts/verification_receipt.py").exists();
    let mut report = String::new();
    report.push_str("# Parallel Receipt Backfill\n\n");
    report.push_str("Generated by `auto parallel receipt-backfill`.\n\n");
    report.push_str("## Preconditions\n\n");
    report.push_str(&format!(
        "- `scripts/run-task-verification.sh`: {}\n",
        present_label(wrapper_present)
    ));
    report.push_str(&format!(
        "- `scripts/verification_receipt.py`: {}\n",
        present_label(recorder_present)
    ));
    report.push_str(&format!(
        "- apply review handoffs: {}\n",
        if apply_handoffs { "yes" } else { "no" }
    ));
    if !applied_handoffs.is_empty() {
        report.push_str(&format!(
            "- applied handoffs: {}\n",
            applied_handoffs.join(", ")
        ));
    }
    report.push('\n');

    if entries.is_empty() {
        report.push_str("No completed task drift detected.\n");
        return report;
    }

    report.push_str("## Tasks Needing Backfill\n\n");
    for entry in entries {
        report.push_str(&format!("### `{}` {}\n\n", entry.task_id, entry.title));
        report.push_str(&format!(
            "- review handoff: {}\n",
            if entry.review_handoff_missing {
                "missing"
            } else {
                "present"
            }
        ));
        if entry.missing_reasons.is_empty() {
            report.push_str("- missing evidence: none reported\n");
        } else {
            report.push_str("- missing evidence:\n");
            for reason in &entry.missing_reasons {
                report.push_str(&format!("  - {reason}\n"));
            }
        }
        if entry.verification_commands.is_empty() {
            report.push_str("- executable verification: none declared\n\n");
            continue;
        }
        report.push_str("- receipt commands:\n\n");
        report.push_str("```bash\n");
        for command in &entry.wrapper_commands {
            report.push_str(command);
            report.push('\n');
        }
        report.push_str("```\n\n");
    }
    report.push_str("## Reconcile After Backfill\n\n");
    report.push_str("After review handoffs and receipt commands are complete, run:\n\n");
    report.push_str("```bash\n");
    report.push_str("AUTO_PARALLEL_TMUX_BOOTSTRAPPED=1 AUTO_SKIP_REMOTE_SYNC=1 auto parallel --max-iterations 0 --threads 2\n");
    report.push_str("```\n");
    report
}

fn present_label(present: bool) -> &'static str {
    if present {
        "present"
    } else {
        "missing"
    }
}

fn review_handoff_changed_files(
    evidence: &crate::completion_artifacts::TaskCompletionEvidence,
) -> Vec<String> {
    if evidence.declared_completion_artifacts.is_empty() {
        Vec::new()
    } else {
        evidence.declared_completion_artifacts.clone()
    }
}

pub(crate) fn render_receipt_wrapper_command(task_id: &str, command: &str) -> String {
    let normalized = normalize_receipt_command(command);
    format!("scripts/run-task-verification.sh {task_id} -- {normalized}")
}

pub(crate) fn normalize_receipt_command(command: &str) -> String {
    let trimmed = command.trim();
    if command_is_shell_harness(trimmed) || !command_needs_shell(trimmed) {
        trimmed.to_string()
    } else {
        format!("bash -lc {}", shell_single_quote(trimmed))
    }
}

fn command_is_shell_harness(command: &str) -> bool {
    command == "bash -lc" || command.starts_with("bash -lc ")
}

fn command_needs_shell(command: &str) -> bool {
    let mut chars = command.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '|' | ';' | '<' | '>' => return true,
            '&' if chars.peek() == Some(&'&') => return true,
            _ => {}
        }
    }
    false
}

fn shell_single_quote(command: &str) -> String {
    format!("'{}'", command.replace('\'', r#"'"'"'"#))
}

#[cfg(test)]
mod tests {
    use super::{
        normalize_receipt_command, render_receipt_backfill_report, render_receipt_wrapper_command,
        ReceiptBackfillEntry,
    };

    #[test]
    fn wrapper_command_normalizes_shell_operators() {
        assert_eq!(
            render_receipt_wrapper_command("TASK-1", "rg -n \"secret\" src || true"),
            "scripts/run-task-verification.sh TASK-1 -- bash -lc 'rg -n \"secret\" src || true'"
        );
        assert_eq!(
            normalize_receipt_command("bash -lc 'rg -n \"secret\" src || true'"),
            "bash -lc 'rg -n \"secret\" src || true'"
        );
    }

    #[test]
    fn backfill_report_includes_commands_and_reconcile_step() {
        let entry = ReceiptBackfillEntry {
            task_id: "TASK-1".to_string(),
            title: "Example".to_string(),
            missing_reasons: vec!["missing REVIEW.md handoff".to_string()],
            review_handoff_missing: true,
            verification_commands: vec!["cargo test example".to_string()],
            wrapper_commands: vec![
                "scripts/run-task-verification.sh TASK-1 -- cargo test example".to_string(),
            ],
        };

        let report = render_receipt_backfill_report(
            std::path::Path::new("/tmp/no-such-repo"),
            false,
            &[],
            &[entry],
        );

        assert!(report.contains("### `TASK-1` Example"));
        assert!(report.contains("missing REVIEW.md handoff"));
        assert!(report.contains("scripts/run-task-verification.sh TASK-1 -- cargo test example"));
        assert!(report.contains("AUTO_PARALLEL_TMUX_BOOTSTRAPPED=1"));
    }
}
